### ISSUE TITLE
Coursera auto answer

### ISSUE THREAD

**Issue by ata284** [bibo318/bibo318#1]
Anh ơi, cái tiện ích coursera này em không sử dụng được ạ, anh giúp em sửa dc không ạ

**Comment by bibo318** [comment]
Cho mình thông tin lỗi b  gặp phải

**Comment by bibo318** [comment]
qua bên này  gửi thông tin lỗi nhé.
[https://github.com/bibo318/coursera-auto-answer/issues](coursera-auto-answer)

**Comment by bibo318** [comment]
Tất các các lỗi qua đúng phần issues bài đó  nhé.
[https://github.com/bibo318/coursera-auto-answer/issues](https://github.com/bibo318/bibo318/issues/coursera-auto-answer)

**Comment by ata284** [comment]
em gửi lên github rồi ạ

Vào Th 5, 7 thg 11, 2024 vào lúc 16:08 Debugs ***@***.***>
đã viết:
