### ISSUE TITLE
lỗi của em đây ạ

### ISSUE THREAD

**Issue by ata284** [bibo318/bibo318#2]
![image](https://github.com/user-attachments/assets/e1ecb29e-c610-45d6-b4c3-4f3130f5d585)

**Comment by bibo318** [comment]
a mới update bản mới e thử lại nhé

**Comment by bibo318** [comment]
![image](https://github.com/user-attachments/assets/adc4e0ed-25bb-4560-b922-4a800b5443e5)

**Comment by bibo318** [comment]
https://github.com/bibo318/coursera-auto-answer

**Comment by ata284** [comment]
vâng ạ, để e thử ạ
em cảm ơn ạ

Vào Th 5, 7 thg 11, 2024 vào lúc 17:00 Debugs ***@***.***>
đã viết:

**Comment by ata284** [comment]
anh ơi, cái key api mình lấy của chatgpt bản không nâng cấp cũng được đúng
không ạ


Vào Th 5, 7 thg 11, 2024 vào lúc 17:15 An Ta ***@***.***> đã
viết:

**Comment by ata284** [comment]
[image: image.png]
[image: image.png]

Vào Th 5, 7 thg 11, 2024 vào lúc 17:23 An Ta ***@***.***> đã
viết:

**Comment by ata284** [comment]
a ơi, cái api của coursera vẫn bị lỗi 404, em fix kiểu gì dc a nhỉ

[image: image.png]

Vào Th 5, 7 thg 11, 2024 vào lúc 17:00 Debugs ***@***.***>
đã viết:

**Comment by bibo318** [comment]
anh lỗi là gì hay lỗi y như trên

**Comment by ata284** [comment]
lỗi y như trên ạ


Vào Th 6, 8 thg 11, 2024 vào lúc 13:49 Debugs ***@***.***>
đã viết:

**Comment by ata284** [comment]
a có thể cập nhập link coursera mới dc kh ạ

Vào Th 6, 8 thg 11, 2024 vào lúc 13:49 Debugs ***@***.***>
đã viết:

**Comment by ata284** [comment]
rất mong a có thể fix được lỗi này ạ

Vào Th 6, 8 thg 11, 2024 lúc 13:49 Debugs ***@***.***> đã
viết:
