### ISSUE TITLE
khi em thay đổi API KEY thì hiện thế này ạ

### ISSUE THREAD

**Issue by ata284** [bibo318/bibo318#3]
![image](https://github.com/user-attachments/assets/e9ce536f-fa76-4a89-ab63-8faa8ef5302d)

**Comment by bibo318** [comment]
Thử lại bản mới xem e nhé 
Thay key "Bearer API-KEY-CHATGPT"
gửi nguyên "Bearer "

**Comment by bibo318** [comment]
![image](https://github.com/user-attachments/assets/d7506e16-6a45-4f0d-b9a8-2ea8845fa61f)

**Comment by bibo318** [comment]
https://github.com/bibo318/coursera-auto-answer
